### ISSUE TITLE
Data Entry: vanilla select dropdown placeholder

### ISSUE THREAD

**Issue by kissmygritts** [oss-wec/wisdm#24]
Make sure to use the follow snippets to get the proper select UI 

``` html
<select required>
  <option value="" disabled>Select Option ...</option>
</select>
```

``` css
select:required:invalid { color: gray; }
option[value=""][disabled] { display: none; }
option { color: black; }
```
